### ISSUE TITLE
No bounce in rbot's junkyard/rumble?

### ISSUE THREAD

**Issue by antdude** [gfax/rbot-plugins#2]
...
11:20AM <Ben> Ant joins the Rumble!
-Ben(~big_f@router.ross154)- You drew: Roundhouse Kick -4, Dodge, Obamacare
          +5, Obamacare +5, Deflector
11:20AM <FngSaiYuk> yep, lots easier
[11:20am] <Ant> what erhfrak!
[11:20am] <Ant> I don't want that game.
[11:20am] <Ant> ugh
11:20AM <FngSaiYuk> t
11:20AM <Ben> It's FngSaiYuk's turn. Roster -- FngSaiYuk: 10 - Mousey: 10 -
          Ant: 10
[11:20am] <Ant> c
-Ben(~big_f@router.ross154)- 1.) Dodge 2.) Obamacare +5 3.) Obamacare +5 4.)
          Deflector 5.) Roundhouse Kick -4
[11:20am] <Ant> t
11:20AM <Ben> It's FngSaiYuk's turn. Roster -- FngSaiYuk: 10 - Mousey: 10 -
          Ant: 10
[11:20am] <Ant> p 4
11:20AM <Ben> <Ant> raises a deflector shield!
-Ben(~big_f@router.ross154)- 1.) Dodge 2.) Obamacare +5 3.) Obamacare +5 4.)
          Roundhouse Kick -4
11:20AM <Mousey> guh
11:20AM <FngSaiYuk> p Mousey 5
11:20AM <Ben> FngSaiYuk plays Nose Bleed -3/1. Respond or pass, Mousey.
11:21AM <Mousey> p 1
11:21AM <Ben> Mousey jumps out of the way and passes FngSaiYuk's attack onto
          <Ant>!
-Ben(~big_f@router.ross154)- 1.) Dodge 2.) Obamacare +5 3.) Obamacare +5 4.)
          Roundhouse Kick -4
11:21AM <Mousey> ha
11:21AM <FngSaiYuk> uh oh
11:21AM <Mousey> lol
[11:21am] \* Ant wait what?
11:21AM <FngSaiYuk> how's this gonna werk
11:21AM <FngSaiYuk> hmm
11:21AM <Mousey> ICN!
11:21AM <FngSaiYuk> t
11:21AM <Ben> Respond to FngSaiYuk or pass, <Ant>. Roster -- FngSaiYuk: 10 -
          Mousey: 10 - <Ant>: 10
11:21AM <FngSaiYuk> cd
11:21AM <Ben> Current discard is Nose Bleed -3/1
[11:21am] <Ant> It doesn't bounce?
11:21AM <Bender> [3:0:0:0] cd/dvd PIONEER DVD-RW DVR-218L 1.02 /dev/sr0
[11:21am] <Ant> cd
11:21AM <Ben> Current discard is Nose Bleed -3/1
11:21AM <FngSaiYuk> interesting
[11:21am] <Ant> t
11:21AM <Ben> Respond to FngSaiYuk or pass, <Ant>. Roster -- FngSaiYuk: 10 -
          Mousey: 10 - <Ant>: 10
[11:21am] <Ant> c
-Ben(~big_f@router.ross154)- 1.) Dodge 2.) Obamacare +5 3.) Obamacare +5 4.)
          Roundhouse Kick -4
11:21AM <Mousey> pa, dammit!
[11:21am] <Ant> p 1
11:21AM <FngSaiYuk> it's your turn right now
11:21AM <Ben> <Ant> dodged and nullified FngSaiYuk's Nose Bleed -3/1!
11:21AM <Ben> It's Mousey's turn.
11:21AM <Mousey> lol
[11:21am] <Ant> Isn't it supposed to bounce?
11:21AM <FngSaiYuk> aww
11:21AM <Mousey> p wo 1 2
11:21AM <Ben> There is no player 'wo'.
11:21AM <Flexo> p wo 5
11:21AM <FngSaiYuk> i wanted to see if it'd bounce or not
[11:21am] <Ant> haha
11:21AM <FngSaiYuk> u shoulda passed
11:21AM <Mousey> pl a 1 2
11:21AM <Bender> Mousey: It's not your turn
1:21AM <Ben> Mousey clutches <Ant>. Pass or respond, <Ant>.
-Ben(~big_f@router.ross154)- 1.) Obamacare +5 2.) Obamacare +5 3.) Roundhouse
          Kick -4
[11:21am] <Ant> oh
[11:21am] <Ant> pass
11:21AM <Ben> Mousey eats some delicious strips of CHUNKY BACON!
11:21AM <Ben> Mousey: 10
-Ben(~big_f@router.ross154)- You drew: Mouse Raid, SHORYUKEN! -5
11:21AM <Ben> It's <Ant>'s turn.
-Ben(~big_f@router.ross154)- 1.) Obamacare +5 2.) Obamacare +5 3.) Mouse Raid
          4.) Roundhouse Kick -4 5.) SHORYUKEN! -5
[11:21am] <Ant> lol
[11:21am] <Ant> cd
11:21AM <Ben> <Ant> hasn't attacked yet.
11:21AM <Bender> cd pl g+2
[11:21am] <Ant> tu
11:21AM <Bender> it's Ant's turn
11:21AM <Ben> It's <Ant>'s turn. Roster -- <Ant>: 10 - FngSaiYuk: 10 - Mousey:
          10
[11:22am] <Ant> ca
11:22AM <Bender> Ant: 7
-Bender(~Bender@0::1)- Your cards:  Green 1   Green 4   Red 7   Red 9   Wild
                       +4   Yellow 1   Yellow Skip
-Ben(~big_f@router.ross154)- 1.) Obamacare +5 2.) Obamacare +5 3.) Mouse Raid
          4.) Roundhouse Kick -4 5.) SHORYUKEN! -5
[11:22am] <Ant> cd
11:22AM <Ben> <Ant> hasn't attacked yet.
11:22AM <FngSaiYuk> it didn't get rid of the deflector
11:22AM <FngSaiYuk> c
[11:22am] <Ant> p Mousey 4
11:22AM <Ben> <Ant> plays Roundhouse Kick -4. Respond or pass, Mousey.
[11:22am] <Ant> Bug?
[11:24am] <Ant> tu
11:24AM <Bender> it's Ant's turn
11:24AM <Ben> Respond to Ant or pass, Mousey. Roster -- <Ant>: 10 - FngSaiYuk:
          10 - Mousey: 10
[11:24am] \* Ant goes back to his VM
11:27AM <FngSaiYuk> oh it's that bug again
...

**Comment by jaythomas** [comment]
Not sure what is happening in this log. Can you explain to me what happened and how to reproduce it?

**Comment by antdude** [comment]
Shouldn't fngsaiyuk's nose bleed -3/1 bounce off my deflector shield?

**Comment by antdude** [comment]
?
